'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { AlertTriangle, CheckCircle2 } from 'lucide-react'

export default function DisclaimerPage() {
  const router = useRouter()
  const [accepted, setAccepted] = useState(false)

  // Removed auto-redirect - user must accept disclaimer every time
  // useEffect removed so localStorage check doesn't auto-forward

  const handleAccept = () => {
    // Store acceptance for current session only
    sessionStorage.setItem('disclaimer-accepted', 'true')
    setAccepted(true)
    setTimeout(() => {
      router.push('/chat')
    }, 500)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
      <div className="max-w-2xl w-full">
        <div className="bg-white rounded-2xl shadow-2xl p-8 md:p-12 border border-gray-100">
          {/* Header */}
          <div className="flex items-center justify-center mb-6">
            <div className="bg-yellow-100 p-4 rounded-full">
              <AlertTriangle className="w-8 h-8 text-yellow-600" />
            </div>
          </div>

          <h1 className="text-3xl md:text-4xl font-bold text-center mb-4 bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Important Disclaimer
          </h1>

          <p className="text-gray-600 text-center mb-8">
            Please read and accept before continuing
          </p>

          {/* Disclaimer Content */}
          <div className="bg-gray-50 rounded-lg p-6 mb-8 space-y-4 max-h-96 overflow-y-auto">
            <div className="space-y-3 text-gray-700 leading-relaxed">
              <p className="font-semibold text-gray-900">
                ⚠️ AI-Generated Content Notice
              </p>
              <p>
                This chatbot uses artificial intelligence to generate responses based on your uploaded PDF documents. 
                Please be aware of the following:
              </p>

              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  <strong>Accuracy:</strong> Responses are generated by AI models and may contain errors, 
                  inaccuracies, or hallucinations. Always verify critical information.
                </li>
                <li>
                  <strong>Citations:</strong> While the system provides source citations, the interpretation 
                  and synthesis of information is AI-generated.
                </li>
                <li>
                  <strong>No Professional Advice:</strong> This tool does not provide legal, medical, financial, 
                  or other professional advice. Consult qualified professionals for such matters.
                </li>
                <li>
                  <strong>Data Privacy:</strong> Your uploaded documents are processed locally and not stored 
                  permanently. However, exercise caution with sensitive information.
                </li>
                <li>
                  <strong>Model Limitations:</strong> AI models have inherent limitations and biases. 
                  Results depend on document quality and query phrasing.
                </li>
              </ul>

              <p className="pt-4 border-t border-gray-200 text-sm text-gray-600">
                By accepting, you acknowledge that you understand these limitations and agree to use 
                this tool as an assistive resource, not as a sole source of truth.
              </p>
            </div>
          </div>

          {/* Accept Button */}
          <Button
            onClick={handleAccept}
            className="w-full h-12 text-lg font-semibold bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 transition-all transform hover:scale-105"
            disabled={accepted}
          >
            {accepted ? (
              <>
                <CheckCircle2 className="mr-2 h-5 w-5" />
                Accepted! Redirecting...
              </>
            ) : (
              'I Understand & Accept'
            )}
          </Button>

          <p className="text-xs text-gray-500 text-center mt-6">
            Version 2.0.0 • Powered by AI
          </p>
        </div>
      </div>
    </div>
  )
}
